### ISSUE TITLE
Plugin running into an error on TeamCity 2023.05.1 (build 129321)

### ISSUE THREAD

**Issue by pmannozg** [redrum-llik/TeamCity-Terraform-Plugin#3]
Latest TeamCity seems to have broken the plugin.

`[15:22:00] : Handle Terraform output (1s)
[15:22:00]i:	 [Handle Terraform output] Parsing report data from the /home/teamcityagent/work/f4cfdd89912cce61/_terraform/envs/*****/*****/*****/*****/plan-15.json
[15:22:02]W: com.fasterxml.jackson.databind.JsonMappingException: toIndex = 4 (through reference chain: jetbrains.buildServer.terraformSupportPlugin.jsonOutput.model.PlanData["resource_changes"]->java.util.ArrayList[33])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:373)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:375)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3542)
	at jetbrains.buildServer.terraformSupportPlugin.TerraformSupport.parsePlanDataFromFile(TerraformSupport.kt:54)
	at jetbrains.buildServer.terraformSupportPlugin.TerraformSupport.handleTerraformOutput(TerraformSupport.kt:158)
	at jetbrains.buildServer.terraformSupportPlugin.TerraformSupport.beforeBuildFinish(TerraformSupport.kt:128)
	at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at jetbrains.buildServer.util.EventDispatcher.invokeListeners(EventDispatcher.java:157)
	at jetbrains.buildServer.util.EventDispatcher.lambda$dispatch$0(EventDispatcher.java:134)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:76)
	at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:134)
	at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:82)
	at com.sun.proxy.$Proxy24.beforeBuildFinish(Unknown Source)
	at jetbrains.buildServer.agent.impl.buildStages.finishStages.FireBeforeBuildFinishFStage.doFinishStage(FireBeforeBuildFinishFStage.java:34)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runCurrentFinishStage(BuildRunActionImpl.java:114)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doBuildFinishStages(BuildRunActionImpl.java:106)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:78)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:345)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:63)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:294)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IndexOutOfBoundsException: toIndex = 4
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:507)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1138)
	at kotlin.collections.CollectionsKt___CollectionsKt.slice(_Collections.kt:864)
	at jetbrains.buildServer.terraformSupportPlugin.jsonOutput.ChangeDeserializer.trimReplacePaths(ChangeDeserializer.kt:258)
	at jetbrains.buildServer.terraformSupportPlugin.jsonOutput.ChangeDeserializer.parseMapValueDelta(ChangeDeserializer.kt:129)
	at jetbrains.buildServer.terraformSupportPlugin.jsonOutput.ChangeDeserializer.parseValueDelta(ChangeDeserializer.kt:65)
	at jetbrains.buildServer.terraformSupportPlugin.jsonOutput.ChangeDeserializer.parseValueDelta$default(ChangeDeserializer.kt:62)
	at jetbrains.buildServer.terraformSupportPlugin.jsonOutput.ChangeDeserializer.deserialize(ChangeDeserializer.kt:49)
	at jetbrains.buildServer.terraformSupportPlugin.jsonOutput.ChangeDeserializer.deserialize(ChangeDeserializer.kt:18)
	at com.fasterxml.jackson.databind.DeserializationContext.readValue(DeserializationContext.java:971)
	at com.fasterxml.jackson.databind.DeserializationContext.readValue(DeserializationContext.java:958)
	at jetbrains.buildServer.terraformSupportPlugin.jsonOutput.ResourceChangeDeserializer.deserialize(ResourceChangeDeserializer.kt:40)
	at jetbrains.buildServer.terraformSupportPlugin.jsonOutput.ResourceChangeDeserializer.deserialize(ResourceChangeDeserializer.kt:13)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	... 31 more
`

**Comment by redrum-llik** [comment]
Hello and sorry about the delayed response here. Can you please open the build where you got this issue, open hidden artifacts (see [the article here](https://www.jetbrains.com/help/teamcity/build-artifact.html#Retrieve+Hidden+Artifacts)) and share the `.teamcity/terraform` folder contents via uploads.jetbrains.com? Please let me know the Upload ID once this is done so I will try to reproduce the issue locally.

**Comment by pmannozg** [comment]
Hi Fedor,

No problem on the late reply.  Not seeing a terraform folder in the hidden artifacts
[cid:fd0ca9fa-1fc5-4b6c-bffb-5b86848e4b99]


PAUL MANNO

Principal DevOps Engineer

[cid:4f5d9ad6-6211-4792-8366-cfbab960f31d]<http://www.zillow.com/>

________________________________

**Comment by redrum-llik** [comment]
Hello Paul, 

I see, thank you. In this case, can you please upload the `.json` file produced as Terraform output? Please feel free to remove any sensitive data as you see fit.

**Comment by pmannozg** [comment]
Hi Fedor,

Sorry, but can't really share that, even sanitized.  I can tell you we are using the following

12:56:44   - Installing hashicorp/random v3.5.1...
12:56:44   - Installed hashicorp/random v3.5.1 (signed by HashiCorp)
12:56:44   - Installing hashicorp/null v3.2.1...
12:56:44   - Installed hashicorp/null v3.2.1 (signed by HashiCorp)
12:56:44   - Installing hashicorp/vsphere v2.4.1...
12:56:45   - Installed hashicorp/vsphere v2.4.1 (signed by HashiCorp)

and this is a plan on vsphere built infrastructure.  And another stack trace

com.fasterxml.jackson.databind.JsonMappingException: toIndex = 4 (through reference chain: jetbrains.buildServer.terraformSupportPlugin.jsonOutput.model.PlanData["resource_changes"]->java.util.ArrayList[38])
  at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
  at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:373)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:375)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
  at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
  at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3542)
  at jetbrains.buildServer.terraformSupportPlugin.TerraformSupport.parsePlanDataFromFile(TerraformSupport.kt:54)
  at jetbrains.buildServer.terraformSupportPlugin.TerraformSupport.handleTerraformOutput(TerraformSupport.kt:158)
  at jetbrains.buildServer.terraformSupportPlugin.TerraformSupport.beforeBuildFinish(TerraformSupport.kt:128)
  at jdk.internal.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at jetbrains.buildServer.util.EventDispatcher.invokeListeners(EventDispatcher.java:157)
  at jetbrains.buildServer.util.EventDispatcher.lambda$dispatch$0(EventDispatcher.java:134)
  at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:76)
  at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:134)
  at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:82)
  at com.sun.proxy.$Proxy24.beforeBuildFinish(Unknown Source)
  at jetbrains.buildServer.agent.impl.buildStages.finishStages.FireBeforeBuildFinishFStage.doFinishStage(FireBeforeBuildFinishFStage.java:34)
  at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runCurrentFinishStage(BuildRunActionImpl.java:114)
  at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doBuildFinishStages(BuildRunActionImpl.java:106)
  at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:78)
  at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:345)
  at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:63)
  at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:294)
  at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IndexOutOfBoundsException: toIndex = 4
  at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:507)
  at java.base/java.util.ArrayList.subList(ArrayList.java:1138)
  at kotlin.collections.CollectionsKt___CollectionsKt.slice(_Collections.kt:864)
  at jetbrains.buildServer.terraformSupportPlugin.jsonOutput.ChangeDeserializer.trimReplacePaths(ChangeDeserializer.kt:258)
  at jetbrains.buildServer.terraformSupportPlugin.jsonOutput.ChangeDeserializer.parseMapValueDelta(ChangeDeserializer.kt:129)
  at jetbrains.buildServer.terraformSupportPlugin.jsonOutput.ChangeDeserializer.parseValueDelta(ChangeDeserializer.kt:65)
  at jetbrains.buildServer.terraformSupportPlugin.jsonOutput.ChangeDeserializer.parseValueDelta$default(ChangeDeserializer.kt:62)
  at jetbrains.buildServer.terraformSupportPlugin.jsonOutput.ChangeDeserializer.deserialize(ChangeDeserializer.kt:49)
  at jetbrains.buildServer.terraformSupportPlugin.jsonOutput.ChangeDeserializer.deserialize(ChangeDeserializer.kt:18)
  at com.fasterxml.jackson.databind.DeserializationContext.readValue(DeserializationContext.java:971)
  at com.fasterxml.jackson.databind.DeserializationContext.readValue(DeserializationContext.java:958)
  at jetbrains.buildServer.terraformSupportPlugin.jsonOutput.ResourceChangeDeserializer.deserialize(ResourceChangeDeserializer.kt:40)
  at jetbrains.buildServer.terraformSupportPlugin.jsonOutput.ResourceChangeDeserializer.deserialize(ResourceChangeDeserializer.kt:13)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
  ... 31 more



PAUL MANNO

Principal DevOps Engineer

[cid:0c4e80fa-ee70-4f44-94f9-fde324712084]<http://www.zillow.com/>

________________________________
